# Node Exporter Values for CloudWatch Integration
# This file configures the prometheus-node-exporter

# Service configuration
service:
  type: ClusterIP
  port: 9100

# Resource limits
resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

# Node selector (optional)
nodeSelector: {}

# Tolerations (optional)
tolerations: []

# Affinity (optional)
affinity: {}

# Additional scrape configs for CloudWatch integration
extraScrapeConfigs: |
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['localhost:9100']
    metrics_path: /metrics
    scrape_interval: 15s
